### PR TITLE
Update 00_Quick_Start_Guide.md

### PR DESCRIPTION
**Pull request by stefanospaziani**
As per Michelangelo's request I better described the behavior of hotspot activation (details in https://community.volumio.org/t/hotspot-fallback-fails-to-start/8796/36)

### CODE REVIEW

**Review by xipmix — COMMENTED** [review]
I strugged to understand this. I've recast the text to see if I understand what you're meaning here. Feel free to use any or none of it. I'm guessing about the watcher in the last line. I think that's what is meant but I don't see that happening in the backend code.

"
* Once your Wireless network has been configured, Volumio will automatically disable the Hotspot
* Volumio can be configured so that if your configured Wireless network is no longer    available (e.g. password change), Volumio will automatically re-enable the Hotspot.
This feature is disabled by default, but can be activated by:                  
  * enabling the option **Hotspot fallback** located in Settings -> Network      
  * and then rebooting

The reboot is necessary because the Hotspot fallback watcher is only activated  
as startup.                                                                     
"

**Comment by stefanospaziani** [comment]
> 
> 
> I strugged to understand this. I've recast the text to see if I understand what you're meaning here. Feel free to use any or none of it. I'm guessing about the watcher in the last line. I think that's what is meant but I don't see that happening in the backend code.
> 
> "
> 
>     * Once your Wireless network has been configured, Volumio will automatically disable the Hotspot
> 
>     * Volumio can be configured so that if your configured Wireless network is no longer    available (e.g. password change), Volumio will automatically re-enable the Hotspot.
>       This feature is disabled by default, but can be activated by:
>       
>       * enabling the option **Hotspot fallback** located in Settings -> Network
>       * and then rebooting
> 
> 
> The reboot is necessary because the Hotspot fallback watcher is only activated
> as startup.
> "

Hi, correct but you must specify that in case of connection lost (drop for any reason), even with Hotspot fallback enabled, a reboot it's necessary. For me it's correct to have the check only at startup instead of having a watchdog in polling but some people figure out "automatically = real time" without rebooting. Let me know further steps to support the project (glad to give my contribution)

**Comment by xipmix** [comment]
Thanks for clarifying this for me. This means my text not correct.
To make sure I have this right - Is it true that to enable fallback one has to turn it on in the settings _and_ reboot?
It sounds like what you're saying is that on top of that there is another case - if you lose wireless connection, even with hotspot fallback enabled, you must reboot for the hotspot to start up?

**Comment by stefanospaziani** [comment]
I try to reply to your questions:

Q: Is it true that to enable fallback one has to turn it on in the settings and reboot?
A: Yes, correct! The behaviour is as expected, IMHO it's not an issue, since the reboot is performed automatically. It's working fine and it's not a problem, at least for me.

Q: if you lose wireless connection, even with hotspot fallback enabled, you must reboot for the hotspot to start up?
A: Yes, you must reboot in order to enable the hotspot. For some people in the forum this is a issue. IMHO it's a nice to have but not a problem due to the fact that a manual intervention is needed in any case (except that I must stand-up from my chair and switch off/on the Raspberry since no remote access is possible).

The "real" issue, at least for me, was the misunderstanding about the default value of the flag, but you are going to update the documentation, so that's fine. Otherwise, if you are not aware and you are not able to reach the UI via wired LAN, the only option is perform a wipe cache.

Hope it's clear now, otherwise happy to go deep

**Comment by xipmix** [comment]
Thanks for the replies, I think we've teased out the details enough now.
So here's your patch.
```
  * Once your Wireless network has been configured, Volumio will automatically disable the Hotspot
- * If, for whatever reason, your configured Wireless network is not available, Volumio will automatically re-enable the Hotspot
+ * If, for whatever reason, your configured Wireless network is not available (e.g. password change), Volumio will automatically re-enable the Hotspot; in case of a connection lost a reboot is needed in order to reactivate the hotspot, since the feature is triggered only at startup. This feature is disabled by default and can be activated by enabling the option **Hotspot fallback** located in Settings -> Network
```
The thing that you're wanting to clarify is what happens if you're in the situation where a wireless network is configured and it then goes away. The hotspot won't turn on unless a) it's configured to do so, which is not the default configuration and b) you reboot.
So how about this
```
  * Once your Wireless network has been configured, Volumio will automatically disable the Hotspot
- * If, for whatever reason, your configured Wireless network is not available, Volumio will automatically re-enable the Hotspot
+ * Volumio can be configured so that if your selected Wireless network is no longer available (e.g. password change),
+   Volumio will start up the Hotspot. This feature is disabled by default, but can be activated by enabling the option **Hotspot fallback** located in Settings -> Network.
+ * To make the Hotspot turn on, you must also reboot Volumio, since the feature is triggered only at startup.
```

**Comment by volumio** [comment]
Thanks!

**Pull request merged**
