### PR TITLE
Documentation for different Rotary Encoder Plugin with Device Tree Overlays

### PR DESCRIPTION
**Pull request by 7h0mas-R**
This is the Documentation for my Plugin `RotaryEncoder II`.
The pull request for the plugin on volumio-plugins is #596

### CODE REVIEW

**Comment by xipmix** [comment]
A lot of work here, congratulations. A small thing I noticed - 'Tipps' should be spelt 'Tips'.

**Comment by xipmix** [comment]
One other thing - you have coded an unordered list as HTML, did the normal syntax for unordered lists not work? https://www.markdownguide.org/basic-syntax/#unordered-lists

**Comment by 7h0mas-R** [comment]
@xipmix Thanks for taking the time to review. I fixed both remarks.
In German, tips are "Tipps" - it's kind of in my ROM code 🤪.
The HTML was an artifact from a previous version, where I had a kind of "hanging" format with explanations in a 2nd line below each bullet. (It is still used at the top of the first page for the Encoder types)
I did not find an implementation for this in MD, so I used HTML. If there is any, I am happy to learn about it.

**Comment by xipmix** [comment]
I did a quick test merge and built the docs, it seems fine. The only thing possibly missing is who the author is - you reference 'Saiyato', maybe it's worth mentioning your own GH name in the first paragraph?

On the bullet lists, it seems what you are describing is close to the 'description list' (```<dl>```) element of HTML. But as you say there doesn't seem to be an equivalent in MD. The only suggestion I can offer is putting a ```<br>``` after the first line, so MD will wrap the line there. But if a real ```<dl>``` makes sense to get your point across, Just Do It (in HTML), I say.

**Comment by 7h0mas-R** [comment]
Thanks again! 
I just removed all HTML now - not 100% happy with the images always scaled to full width, but since this is also used on the other Doc pages, I also see the beauty of a consistent look 🙃

**Pull request merged**
